{
  imports = [
    ./alacritty.nix
    ./bottom.nix
    ./btop.nix
    ./direnv.nix
    ./gecko/firefox.nix
    ./git.nix
    ./helm.nix
    ./gecko/librewolf.nix
    ./k9s.nix
    ./lazygit.nix
    ./ssh.nix
    ./starship.nix
    ./tmux.nix
    ./yazi.nix
    ./zsh.nix
  ];
}
